require("dotenv").config();
const express = require("express");
const app = express();
const axios = require("axios");
const Snoowrap = require("snoowrap");
const { CommentStream } = require("snoostorm");

const { CLIENT_SECRET, CLIENT_ID, REDDIT_USER, REDDIT_PASS } = process.env;
const client = new Snoowrap({
  userAgent: "dOnTqUoTeMeOnThAt-bot",
  clientId: CLIENT_ID,
  clientSecret: CLIENT_SECRET,
  username: REDDIT_USER,
  password: REDDIT_PASS
});

const comments = new CommentStream(client, {
  subreddit: "testingground4bots",
  limit: 10,
  pollTime: 120000
});
const BOT_START = Date.now() / 1000;

const createReply = post => {
    const reply = post.body.split('but dont quote me on that')[0];
    return `"${reply}" - ${post.author.name}`
};

comments.on("item", item => {
    if (item.created_utc < BOT_START) return;
    console.log(item.body);
    // if (item.body.includes('but dont quote me on that')) { 
    //     console.log('AYYY')
    //     item.reply(createReply(item))
    // }
    item.reply(`I am bot. I dont know what I do yet. Here have a number randomly generated by JavaScript for now I guess ${Math.random() * 1000}`);
});

app.listen(process.env.PORT, () =>
  console.log(`Server live on ${process.env.PORT}`)
);
